name: siipnemovil_v2
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.12.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  flutter_dotenv: ^6.0.1 #leer .env
  image_picker: ^1.2.3 #Obtener img de la camara o galeria
  flutter_pdfview: ^1.4.4 #Visaulizar PDF
  dropdown_search: ^7.0.0 #Combo con busqueda
  #url_launcher: ^6.3.1 # Abrir Urls - lo trae desde el paquete de mi upp
  #share_plus: ^10.1.1 # Compartir archivos - lo trae desde el paquete de mi upp
  #awesome_dialog: ^3.2.1 #Dialogos - lo trae desde el paquete de mi upp
  #image: ^4.5.4 #Para trabajar con imagenes de la galeria - lo trae desde el paquete de mi upp
  #shared_preferences: ^2.5.3 - lo trae desde el paquete de mi upp
  #END DEFAULF


  # LIBREARIAS GPS
  flutter_bloc: ^9.1.1 #Mapas
  bloc: ^9.2.1
  equatable: ^2.1.0
  #permission_handler: ^12.0.0 # Solicita Permisos del dispositivo al usuario (Ubicacion,Galeria.....) - lo trae desde el paquete de mi upp
  geolocator: ^14.0.3 #ubicacion Gps, del dispositivo
  flutter_map: ^8.3.1 #0.9.0 #mapas openstreetmap (TRAE latlong)
  flutter_map_marker_popup: ^8.1.1
  # END LIBREARIAS GPS


  # NECESARIOS QR
  qr_code_scanner_plus: ^2.2.0 #Qr Scan reemplaza a qr_code_scanner: ^1.0.1
  zxing2: ^0.2.4 #Leer data de qr desde Galeria
  qr_flutter: ^4.1.0 #Generar Qr
  # END QR


  syncfusion_flutter_gauges: ^34.1.32 #Diseño de clave digital

  #NOTIFICACIONES PUSH
  firebase_core: ^4.12.1
  firebase_messaging: ^16.4.3
  flutter_local_notifications: ^22.1.0


  sqflite: ^2.4.3



  api_provider:
    git:
      url: https://github.com/freddycalderonp1990/paquete_api_provider.git
      ref: 1.0.5

  app_mi_upc:
    git:
      url: https://github.com/freddycalderonp1990/app_mi_upc.git
      ref: 4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  mocktail: ^1.0.4

# flutter pub run flutter_launcher_icons:main


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon_app.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/icon_app.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon/icon_app.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/icon_app.png"


  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/
    - assets/icon/
    - assets/siipne_movil/icon/
    - assets/siipne_movil/op_servicio_urbano/
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Arial
      fonts:
        - asset: assets/fonts/arial_bold.ttf
          weight: 700
        - asset: assets/fonts/arial_bold_italic.ttf
          weight: 300
        - asset: assets/fonts/arial_italic.ttf
          weight: 600
        - asset: assets/fonts/arial_regular.ttf
          weight: 400

    - family: Bookman Old Style
      fonts:
        - asset: assets/fonts/bookman_old_style_bold.ttf
          weight: 400
        - asset: assets/fonts/bookman_old_style_bold_italic.ttf
          weight: 400
        - asset: assets/fonts/bookman_old_style_italic.ttf
          weight: 400
        - asset: assets/fonts/bookman_old_style_regular.ttf
          weight: 400


    - family: Century Gothic
      fonts:
        - asset: assets/fonts/century_gothic_bold.ttf
          weight: 700
        - asset: assets/fonts/century_gothic_bold_italic.ttf
          weight: 300
        - asset: assets/fonts/century_gothic_italic.ttf
          weight: 600
        - asset: assets/fonts/century_gothic_regular.ttf
          weight: 400
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
