storePassword=policiaEcuadorSiipneMovil2
keyPassword=policiaEcuadorSiipneMovil2
keyAlias=PoliciaSiipneMovil2
storeFile=/Users/policianacional/AndroidStudioProjects/siipnemovil_v2/api_key/keyAppSiipneMovil2.jks





