storePassword=policiaEcuadorSiipneMovil2
keyPassword=policiaEcuadorSiipneMovil2
keyAlias=PoliciaSiipneMovil2
storeFile=/Users/policianacional/AndroidStudioProjects/siipnemovil2/api_key/keyAppSiipneMovil2.jks





