// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgzOlXeav_XMKw3mXPxx6OkhQuFFmwnVY',
    appId: '1:862175613623:android:74488488c466b0747bf332',
    messagingSenderId: '862175613623',
    projectId: 'crypto-2025-jp',
    storageBucket: 'crypto-2025-jp.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABCua2weTxEOwu7INX7gb-saxV-bI8h3M',
    appId: '1:862175613623:ios:a3f3f58e931e34d07bf332',
    messagingSenderId: '862175613623',
    projectId: 'crypto-2025-jp',
    storageBucket: 'crypto-2025-jp.firebasestorage.app',
    iosBundleId: 'ecuador.policianacional.dntic.siipnemovilV2',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdX3UWjDVH92c411clFmRJQV6Gd9ZtQaM',
    appId: '1:862175613623:web:026ef8494a9a6acb7bf332',
    messagingSenderId: '862175613623',
    projectId: 'crypto-2025-jp',
    authDomain: 'crypto-2025-jp.firebaseapp.com',
    storageBucket: 'crypto-2025-jp.firebasestorage.app',
    measurementId: 'G-CD7TK5EFYL',
  );
}
